'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
type Player={id:string;nickname:string;best:number;runs:number;rank:number|null;longest:number};
type Board={players:Player[];mine:Player;total:number;page:number};
async function api(path:string,body?:unknown){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(r.status===401){location.assign('/');throw new Error('Please sign in.');}if(!r.ok)throw new Error(d.error||'Please try again.');return d;}
export default function Arcade({signOutPath}:{signOutPath:string}){
 const[profile,setProfile]=useState<{id:string;nickname:string}|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[name,setName]=useState(''),[saving,setSaving]=useState(false),[board,setBoard]=useState<Board|null>(null),[page,setPage]=useState(1),[boardError,setBoardError]=useState(''),[lastScore,setLastScore]=useState<number|null>(null);const frame=useRef<HTMLIFrameElement>(null);
 const loadProfile=useCallback(async()=>{setError('');setLoading(true);try{const d=await api('/api/profile');setProfile(d.profile);}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
 const refresh=useCallback(async()=>{try{setBoardError('');const d=await api('/api/leaderboard?page='+page);setBoard(d);}catch(e){setBoardError((e as Error).message);}},[page]);
 useEffect(()=>{void loadProfile();},[loadProfile]);useEffect(()=>{if(profile)void refresh();},[profile,refresh]);
 useEffect(()=>{function receive(e:MessageEvent){if(e.origin!==location.origin||e.source!==frame.current?.contentWindow)return;if(e.data?.type==='neon-score-saved'){setLastScore(e.data.score);void refresh();}}window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[refresh]);
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{await api('/api/profile',{nickname:name});await loadProfile();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 return <main className="arcade-shell"><header className="site-header"><a className="brand" href="/">ϟ NEON RIFT</a><div className="account-links">{profile&&<span>{profile.nickname} <small>#{profile.id.slice(0,4)}</small></span>}<Button variant="ghost" onClick={async()=>{try{const d=await api('/api/auth/logout',{});location.assign(d.next||signOutPath);}catch(e){setError((e as Error).message);}}}>Sign out</Button></div></header>
 {loading?<section className="setup-card"><h1>Loading your player profile…</h1></section>:!profile?<section className="setup-card"><span className="eyebrow">PLAYER SETUP</span><h1>What should we call you?</h1><p>Choose the nickname other players will see beside your score.</p><form onSubmit={save}><label htmlFor="nickname">Player nickname</label><Input id="nickname" value={name} onChange={e=>setName(e.target.value)} required minLength={3} maxLength={20} placeholder="e.g. RiftRunner" autoComplete="nickname"/><p className="fineprint">3–20 characters. This name appears on the leaderboard.</p><Button size="lg" disabled={saving}>{saving?'Saving…':'Enter the arcade'}</Button></form>{error&&<p role="alert" className="error">{error} <Button variant="outline" onClick={loadProfile}>Retry</Button></p>}</section>:<>
 {error&&<p className="error" role="alert">{error}</p>}<section className="scorecards" aria-label="Your score card"><div><span>YOUR RANK</span><strong>{board?.mine.rank?'#'+board.mine.rank:'—'}</strong><small>{board?`Among ${board.total} ranked players`:'Loading rankings…'}</small></div><div><span>PERSONAL BEST</span><strong>{board?board.mine.best.toLocaleString():'—'}</strong><small>Saved to your account</small></div><div><span>COMPLETED RUNS</span><strong>{board?board.mine.runs:'—'}</strong><small>{board?.mine.longest?`Longest survival: ${(board.mine.longest/1000).toFixed(1)}s`:'Finish a run to get ranked'}</small></div><div><span>LAST RUN</span><strong>{lastScore===null?'—':lastScore.toLocaleString()}</strong><small>{lastScore===null?'Your next score starts below':'Score saved successfully'}</small></div></section>
 <iframe ref={frame} title="Neon Rift survival game" className="game-frame" src="/arcade/index.html"/>
 <section className="leaderboard" aria-label="All player rankings"><div className="board-heading"><div><span className="eyebrow">EVERY RUN COUNTS</span><h2>Leaderboard</h2><p>All players · Best score per player · Equal scores share a rank</p></div><Button variant="outline" onClick={refresh}>Refresh rankings</Button></div>{boardError?<p className="error" role="alert">{boardError}</p>:!board?<p>Loading rankings…</p>:board.players.length===0?<div className="empty-board">No completed runs yet. Finish your first run to take a place on the board.</div>:<Table><TableHeader><TableRow><TableHead>Rank</TableHead><TableHead>Player</TableHead><TableHead>Best score</TableHead><TableHead>Runs</TableHead></TableRow></TableHeader><TableBody>{board.players.map(p=><TableRow key={p.id} className={p.id===profile.id?'your-row':''}><TableCell><span className={p.rank&&p.rank<=3?'top-rank':''}>#{p.rank}</span></TableCell><TableCell>{p.nickname} <small>#{p.id.slice(0,4)}</small>{p.id===profile.id&&<span className="you-tag">YOU</span>}</TableCell><TableCell className="score-number">{p.best.toLocaleString()}</TableCell><TableCell>{p.runs}</TableCell></TableRow>)}</TableBody></Table>}
 {board&&board.total>20&&<div className="pages"><Button variant="outline" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</Button><span>Page {page} of {Math.ceil(board.total/20)}</span><Button variant="outline" disabled={page*20>=board.total} onClick={()=>setPage(p=>p+1)}>Next</Button></div>}</section></>}
 <footer className="site-footer">NEON RIFT · BUILT FOR PRAKASH</footer></main>
}
