const fs=require('fs'),vm=require('vm'),ts=require('typescript'),assert=require('node:assert/strict'),bcrypt=require('bcryptjs'),{DatabaseSync}=require('node:sqlite');
const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+file,'utf8'));
function prepare(sql,args=[]){return {bind(...a){return prepare(sql,a)},async first(){return sqlite.prepare(sql).get(...args)||null},async run(){return sqlite.prepare(sql).run(...args)},async all(){return {results:sqlite.prepare(sql).all(...args)}}};}
const db={prepare,async batch(statements){sqlite.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());sqlite.exec('COMMIT');return out;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
let jar=new Map(),lastOptions;const cookieApi={get:n=>jar.has(n)?{value:jar.get(n)}:undefined,set(n,v,o){jar.set(n,v);lastOptions=o;}};
function load(file,dependencies){const sandbox={exports:{},require:n=>dependencies[n],crypto,TextEncoder,Date,console};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,sandbox);return sandbox.exports;}
const auth=load('lib/username-auth.ts',{'bcryptjs':bcrypt,'next/headers':{cookies:async()=>cookieApi},'@/db':{database:()=>db}});
const request=new Request('https://game.test/api/auth/signup',{headers:{'cf-connecting-ip':'192.0.2.1'}});
(async()=>{assert.equal(await auth.gameUser(),null);await assert.rejects(auth.authenticate('signup',{username:'with@email',password:'StrongPassword123',confirmPassword:'StrongPassword123'},request));await assert.rejects(auth.authenticate('signup',{username:'alice',password:'short',confirmPassword:'short'},request));await auth.authenticate('signup',{username:'Alice',password:'StrongPassword123',confirmPassword:'StrongPassword123'},request);const alice=await auth.gameUser();assert.equal(alice.username,'alice');assert(lastOptions.httpOnly&&lastOptions.secure&&lastOptions.sameSite==='lax');let token=jar.get('__Host-neon_session');assert.equal(token.length,64);const account=sqlite.prepare('SELECT * FROM accounts').get();assert.notEqual(account.password_hash,'StrongPassword123');assert.equal(bcrypt.getRounds(account.password_hash),12);assert.notEqual(sqlite.prepare('SELECT token_hash FROM sessions').get().token_hash,token);
await assert.rejects(auth.authenticate('signup',{username:'ALICE',password:'StrongPassword123',confirmPassword:'StrongPassword123'},request),e=>e.status===409);await auth.signOut();assert.equal(await auth.gameUser(),null);jar.set('__Host-neon_session',token);assert.equal(await auth.gameUser(),null);jar.clear();await assert.rejects(auth.authenticate('login',{username:'alice',password:'WrongPassword123'},request),e=>e.status===401);await auth.authenticate('login',{username:'ALICE',password:'StrongPassword123'},request);assert.equal((await auth.gameUser()).userId,alice.userId);sqlite.prepare('UPDATE sessions SET expires_at=0').run();assert.equal(await auth.gameUser(),null);jar.clear();await auth.authenticate('signup',{username:'bob',password:'OtherPassword123',confirmPassword:'OtherPassword123'},request);assert.notEqual((await auth.gameUser()).userId,alice.userId);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM players').get().n,2);
const key=await auth.digest('login:username:alice');sqlite.prepare('UPDATE auth_limits SET attempts=12,expires_at=? WHERE key=?').run(Date.now()+60000,key);await assert.rejects(auth.authenticate('login',{username:'alice',password:'StrongPassword123'},request),e=>e.status===429);
console.log('Passed: username validation, password hashing, unique case-insensitive signup, login, wrong password, secure session cookies, hashed tokens, logout revocation, expired sessions, separate player identities and rate limiting.');})().catch(e=>{console.error(e);process.exitCode=1});
