'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
export default function AuthForm(){
 const[mode,setMode]=useState('login'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirmPassword,setConfirm]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[signedIn,setSignedIn]=useState(false);
 useEffect(()=>{fetch('/api/auth/me',{cache:'no-store'}).then(r=>r.json()).then(d=>setSignedIn(d.authenticated)).catch(()=>{});},[]);
 function change(value:string){if(busy)return;setMode(value);setError('');setPassword('');setConfirm('');}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(mode==='signup'&&password!==confirmPassword){setError('Passwords do not match.');return;}setBusy(true);try{const r=await fetch('/api/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password,confirmPassword})});const d=await r.json();if(!r.ok)throw Error(d.error);location.assign('/play');}catch(e){setError((e as Error).message||'Connection failed. Please try again.');}finally{setBusy(false);}}
 return <div className="account-auth"><span className="eyebrow">{mode==='signup'?'JOIN THE ARCADE':'PLAYER LOGIN'}</span><h2>{mode==='signup'?'Choose your player identity.':'Welcome back, player.'}</h2><p className="auth-description">Just a username and password. Jump in and claim your rank.</p><Tabs value={mode} onValueChange={change}><TabsList className="auth-tabs"><TabsTrigger value="login" disabled={busy}>Log in</TabsTrigger><TabsTrigger value="signup" disabled={busy}>Sign up</TabsTrigger></TabsList></Tabs>
 <form onSubmit={submit}><label htmlFor="username">Username</label><Input id="username" autoComplete="username" autoCapitalize="none" spellCheck={false} value={username} onChange={e=>setUsername(e.target.value)} minLength={3} maxLength={20} pattern="[A-Za-z0-9_]{3,20}" required placeholder="e.g. prakash_20"/><span className="password-help">3–20 letters, numbers or underscores. Not case-sensitive.</span><label htmlFor="password">Password</label><div className="password-field"><Input id="password" type={show?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} minLength={10} maxLength={72} required/><Button type="button" variant="ghost" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?'Hide':'Show'}</Button></div><span className="password-help">At least 10 characters.</span>{mode==='signup'&&<><label htmlFor="confirm">Confirm password</label><Input id="confirm" type={show?'text':'password'} autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirm(e.target.value)} minLength={10} maxLength={72} required/></>}
 {error&&<p className="error" role="alert">{error}</p>}<Button type="submit" size="lg" className="auth-submit" disabled={busy}>{busy?'Please wait…':mode==='login'?'Log in & play':'Create account & play'}</Button></form>{signedIn&&<a className="continue-link" href="/play">Continue your signed-in game →</a>}<p className="privacy">Your player name and scores appear on the leaderboard. Keep your username and password safe; account recovery is not available.</p></div>
}
